### ISSUE TITLE
How to set Proxy from the Kameleo API?

### ISSUE THREAD

**Issue by JonathanR25** [kameleo-io/local-api-client-csharp#4]
What would be the proper code syntax form to set the Proxy details/credentials from the Kameleo API?

Also, could your provide some example code?

**Comment by MBailey01** [comment]
Below you can see the example of how to set up a proxy using the Local API Clients which you are free to use:

```
    var createProfileRequest = BuilderForCreateProfile
      .ForBaseProfile(baseProfileList[0].Id)
      .SetRecommendedDefaults()
      .SetProxy("socks5", new Server("<proxy_host>", <proxy_port>, "<username>", "<password>"))
      .Build();
    
    var profile = await client.CreateProfileAsync(createProfileRequest);
```

These answers are provided from the Kameleo [Set Proxy from API](https://help.kameleo.io/hc/en-us/articles/4455243268625-Set-Proxy-from-API) article.
